create table guests (id bigint generated by default as identity, name varchar(255), surname varchar(255), primary key (id))
create table movies (id bigint generated by default as identity, title varchar(255), primary key (id))
create table rooms (id bigint generated by default as identity, number_of_seats integer not null, room_name varchar(255), primary key (id))
create table seats (id bigint generated by default as identity, available boolean not null, seat_number integer not null, room_id bigint, primary key (id))
create table tickets (id bigint generated by default as identity, price float not null, seat_number integer not null, type varchar(255), guest_id bigint, timetable_id bigint, primary key (id))
create table timetables (id bigint generated by default as identity, guests_number integer not null, session_date DATE, session_time TIME, movie_id bigint, room_id bigint, primary key (id))
alter table seats add constraint FKg993pi7ucgy616icmddq8u335 foreign key (room_id) references rooms
alter table tickets add constraint FKso213ljf4xxgnwh05vymbtwu foreign key (guest_id) references guests
alter table tickets add constraint FKprsw8ecusdah39hlnopa1j1ac foreign key (timetable_id) references timetables
alter table timetables add constraint FKofc1ermbveldhpvfo4c0gkut8 foreign key (movie_id) references movies
alter table timetables add constraint FKskk5bd8w1imseo6ardau7fblx foreign key (room_id) references rooms
create table guests (id bigint generated by default as identity, name varchar(255), surname varchar(255), primary key (id))
create table movies (id bigint generated by default as identity, title varchar(255), primary key (id))
create table rooms (id bigint generated by default as identity, number_of_seats integer not null, room_name varchar(255), primary key (id))
create table seats (id bigint generated by default as identity, available boolean not null, seat_number integer not null, room_id bigint, primary key (id))
create table tickets (id bigint generated by default as identity, price float not null, seat_number integer not null, type varchar(255), guest_id bigint, timetable_id bigint, primary key (id))
create table timetables (id bigint generated by default as identity, guests_number integer not null, session_date DATE, session_time TIME, movie_id bigint, room_id bigint, primary key (id))
alter table seats add constraint FKg993pi7ucgy616icmddq8u335 foreign key (room_id) references rooms
alter table tickets add constraint FKso213ljf4xxgnwh05vymbtwu foreign key (guest_id) references guests
alter table tickets add constraint FKprsw8ecusdah39hlnopa1j1ac foreign key (timetable_id) references timetables
alter table timetables add constraint FKofc1ermbveldhpvfo4c0gkut8 foreign key (movie_id) references movies
alter table timetables add constraint FKskk5bd8w1imseo6ardau7fblx foreign key (room_id) references rooms
