

CREATE TABLE guests (id bigint GENERATED BY DEFAULT AS IDENTITY, name VARCHAR(30), surname VARCHAR(30), PRIMARY KEY (id))
CREATE TABLE movies (id bigint GENERATED BY DEFAULT AS IDENTITY, title VARCHAR(50), PRIMARY KEY (id))
CREATE TABLE rooms (id bigint GENERATED BY DEFAULT AS IDENTITY, room_name VARCHAR(30), number_of_seats INTEGER NOT NULL, PRIMARY KEY (id))
CREATE TABLE tickets (id bigint GENERATED BY DEFAULT AS IDENTITY,ticket_type VARCHAR(30), price FLOAT NOT NULL, seat_number INTEGER NOT NULL,session_date DATE, session_time TIME, guest_id bigint, timetable_id bigint, PRIMARY KEY (id))
CREATE TABLE timetables (id bigint GENERATED BY DEFAULT AS IDENTITY, session_time TIME, session_date DATE, movie_id bigint, room_id bigint, PRIMARY KEY (id))
CREATE TABLE seats (id bigint GENERATED BY DEFAULT AS IDENTITY, seat_number INTEGER NOT NULL, room_id bigint, PRIMARY KEY (id))

ALTER TABLE tickets ADD CONSTRAINT FKso213ljf4xxgnwh05vymbtwu FOREIGN KEY (guest_id) REFERENCES guests
ALTER TABLE tickets ADD CONSTRAINT FKprsw8ecusdah39hlnopa1j1ac FOREIGN KEY (timetable_id) REFERENCES timetables
ALTER TABLE timetables ADD CONSTRAINT FKofc1ermbveldhpvfo4c0gkut8 FOREIGN KEY (movie_id) REFERENCES movies
ALTER TABLE timetables ADD CONSTRAINT FKskk5bd8w1imseo6ardau7fblx FOREIGN KEY (room_id) REFERENCES rooms
ALTER TABLE seats ADD CONSTRAINT FKg993pi7ucgy616icmddq8u335 FOREIGN KEY (room_id) REFERENCES rooms

