

CREATE TABLE guests (id bigint GENERATED BY DEFAULT AS IDENTITY, name varchar(30), surname varchar(30), PRIMARY KEY (id))
CREATE TABLE movies (id bigint GENERATED BY DEFAULT AS IDENTITY, title varchar(50), PRIMARY KEY (id))
CREATE TABLE rooms (id bigint GENERATED BY DEFAULT AS IDENTITY, room_name varchar(30), number_of_seats INTEGER NOT NULL, PRIMARY KEY (id))
CREATE TABLE tickets (id bigint GENERATED BY DEFAULT AS IDENTITY,type varchar(30), price FLOAT NOT NULL, seat_number INTEGER NOT NULL,session_date DATE, session_time TIME, guest_id bigint, timetable_id bigint, PRIMARY KEY (id))
CREATE TABLE timetables (id bigint GENERATED BY DEFAULT AS IDENTITY, session_time TIME, session_date DATE, movie_id bigint, room_id bigint, PRIMARY KEY (id))
create table seats (id bigint generated by default as identity, seat_number integer not null, room_id bigint, primary key (id))

ALTER TABLE tickets ADD CONSTRAINT FKso213ljf4xxgnwh05vymbtwu FOREIGN KEY (guest_id) REFERENCES guests
ALTER TABLE tickets ADD CONSTRAINT FKprsw8ecusdah39hlnopa1j1ac FOREIGN KEY (timetable_id) REFERENCES timetables
ALTER TABLE timetables ADD CONSTRAINT FKofc1ermbveldhpvfo4c0gkut8 FOREIGN KEY (movie_id) REFERENCES movies
ALTER TABLE timetables ADD CONSTRAINT FKskk5bd8w1imseo6ardau7fblx FOREIGN KEY (room_id) REFERENCES rooms
alter table seats add constraint FKg993pi7ucgy616icmddq8u335 foreign key (room_id) references rooms



/*OLD VERSION ========================================================================== */
/*
CREATE TABLE guests (id bigint GENERATED BY DEFAULT AS IDENTITY, name VARCHAR(50) NOT NULL, surname VARCHAR(50) NOT NULL, PRIMARY KEY (id))
CREATE TABLE guests_tickets_list (guest_id bigint NOT NULL, tickets_list_id bigint NOT NULL)
CREATE TABLE movies (id bigint GENERATED BY DEFAULT AS IDENTITY, title VARCHAR(50) NOT NULL, PRIMARY KEY (id))
CREATE TABLE movies_timetable_list (movie_id bigint NOT NULL, timetable_list_id bigint NOT NULL)
CREATE TABLE rooms (id bigint GENERATED BY DEFAULT AS IDENTITY,room_name VARCHAR(50) NOT NULL, number_of_seats INTEGER NOT NULL, PRIMARY KEY (id))
CREATE TABLE rooms_timetable_list (room_id bigint NOT NULL, timetable_list_id bigint NOT NULL)
CREATE TABLE tickets (id bigint GENERATED BY DEFAULT AS IDENTITY, type VARCHAR(50) NOT NULL,  price float NOT NULL, PRIMARY KEY (id))
CREATE TABLE timetables (id bigint GENERATED BY DEFAULT AS IDENTITY, guests_number INTEGER NOT NULL, session_time TIME NOT NULL, session_date DATE NOT NULL, PRIMARY KEY (id))
CREATE TABLE timetables_tickets_list (timetable_id bigint NOT NULL, tickets_list_id bigint NOT NULL)

ALTER TABLE guests_tickets_list ADD CONSTRAINT UK_jtjyrelysr3t2s66a9gcc13t8 UNIQUE (tickets_list_id)
ALTER TABLE movies_timetable_list ADD CONSTRAINT UK_h67w3gybeq2iawocceogm9274 UNIQUE (timetable_list_id)
ALTER TABLE rooms_timetable_list ADD CONSTRAINT UK_tfalbjebdd4ih9fdhuk65ygl4 UNIQUE (timetable_list_id)
ALTER TABLE timetables_tickets_list ADD CONSTRAINT UK_sg31168ub9gkkgve5gatj4rjt UNIQUE (tickets_list_id)
ALTER TABLE guests_tickets_list ADD CONSTRAINT FKpvkkwa1sdy3klvb27m1ar4343 FOREIGN KEY (tickets_list_id) REFERENCES tickets
ALTER TABLE guests_tickets_list ADD CONSTRAINT FKojarqgn2fsd5eo9u921lv9mgt FOREIGN KEY (guest_id) REFERENCES guests
ALTER TABLE movies_timetable_list ADD CONSTRAINT FKac96aa1qrf1e7gonxgx96ebx5 FOREIGN KEY (timetable_list_id) REFERENCES timetables
ALTER TABLE movies_timetable_list ADD CONSTRAINT FKnm9k3dn0n5u54sa2y7tkv2oq4 FOREIGN KEY (movie_id) REFERENCES movies
ALTER TABLE rooms_timetable_list ADD CONSTRAINT FKqmp4u595b0b7qmp8qggpjjbh9 FOREIGN KEY (timetable_list_id) REFERENCES timetables
ALTER TABLE rooms_timetable_list ADD CONSTRAINT FKmym8ntxjmva8oh0499e0hyvdr FOREIGN KEY (room_id) REFERENCES rooms
ALTER TABLE timetables_tickets_list ADD CONSTRAINT FKaefc2f18hvdc9q3f4128q0xum FOREIGN KEY (tickets_list_id) REFERENCES tickets
ALTER TABLE timetables_tickets_list ADD CONSTRAINT FKb1epefe0veirh2rcuv35jb6mo FOREIGN KEY (timetable_id) REFERENCES timetables
*/


